// src/constants/api/fields.js
// Whitelists de campos por recurso para Sparse Fieldsets (?fields=)
//
// - permitidos:  campos que el cliente PUEDE pedir (y que se devuelven)
// - default:     campos que se devuelven si no viene ?fields=
// - sensitive:   campos que NUNCA se devuelven ni se pueden pedir

export const CAMPOS_USUARIO = {
  permitidos: [
    "id",
    "name",
    "email",
    "telefono",
    "telefonos",
    "image_url",
    "public_id",
    "rol",
    "provider",
    "email_verificado",
    "ultimo_login",
    "created_at",
    "updated_at",
  ],
  default: ["id", "name", "email", "rol", "telefono", "image_url"],
  sensitive: [
    "password",
    "codigo_verificacion",
    "date_codigo_verificacion",
    "bloqueado",
    "intentos_fallidos",
    "provider_id",
  ],
};

export const CAMPOS_PROPIEDAD = {
  permitidos: [
    "id",
    "operation_type_id",
    "property_type_id",
    "condition_type_id",
    "heating_type_id",
    "rental_type_id",
    "country_id",
    "state_id",
    "city_id",
    "barrio_id",
    "titulo",
    "description",
    "direccion",
    "numero_direccion",
    "floor",
    "interior_apartment_number",
    "postal_code",
    "latitude",
    "longitude",
    "estrato",
    "precio",
    "price_per_sqm",
    "administracion",
    "constructed_area",
    "private_area",
    "plot_area",
    "room_count",
    "bedroom_count",
    "bathroom_count",
    "social_bathroom_count",
    "construction_year",
    "antiguedad_anios",
    "is_new_construction",
    "parqueadero_tipo",
    "parqueadero_modo",
    "parking_space_count",
    "parking_space_included",
    "parking_space_price",
    "tiene_agua",
    "tiene_luz",
    "tiene_gas",
    "tiene_alcantarillado",
    "has_elevator",
    "has_swimming_pool",
    "has_gym",
    "has_security_24h",
    "has_air_conditioning",
    "is_furnished",
    "zona",
    "estado",
    "listing_status",
    "published_at",
    "expires_at",
    "publicado_por_id",
    "organizacion_id",
    "es_de_organizacion",
    "how_to_contact",
    "telefono_contacto",
    "barrio_nombre",
    "cedula_catastral",
    "matricula_inmobiliaria",
    "created_at",
    "updated_at",
  ],
  default: [
    "id",
    "titulo",
    "direccion",
    "precio",
    "price_per_sqm",
    "estrato",
    "bedroom_count",
    "bathroom_count",
    "private_area",
    "constructed_area",
    "imagen_principal_url",
  ],
  sensitive: ["geom"],
};

export const CAMPOS_ORGANIZACION = {
  permitidos: [
    "id",
    "nombre",
    "email",
    "telefono",
    "website",
    "descripcion",
    "logo_url",
    "logo_public_id",
    "ciudad",
    "provincia",
    "slug",
    "tema",
    "estado",
    "custom_domain",
    "dominio_estado",
    "plan",
    "created_at",
    "updated_at",
  ],
  default: ["id", "nombre", "slug", "logo_url", "ciudad", "provincia", "telefono"],
  sensitive: ["creada_por_id"],
};

export const CAMPOS_MIEMBRO = {
  permitidos: [
    "id",
    "usuario_id",
    "organizacion_id",
    "rol_en_org",
    "estado",
    "created_at",
    "updated_at",
    "name",
    "email",
    "telefono",
    "image_url",
  ],
  default: ["id", "usuario_id", "name", "email", "rol_en_org", "estado", "image_url"],
  sensitive: [],
};

export const CAMPOS_LEAD = {
  permitidos: [
    "id",
    "propiedad_id",
    "nombre",
    "email",
    "telefono",
    "score",
    "origen",
    "estado",
    "notificado",
    "created_at",
    "updated_at",
    "propiedad_titulo",
  ],
  default: ["id", "nombre", "email", "telefono", "estado", "score", "origen", "created_at"],
  sensitive: ["sesion_id", "usuario_id"],
};
