name: Deploy Backend

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: SSH Deploy
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      echo "🚀 Iniciando despliegue..."

                      cd /var/www/inmobitwo/backend-inmobitwo

                      git pull origin main

                      echo "→ Reconstruyendo y levantando contenedor..."
                      docker compose up -d --build

                      echo "→ Limpiando imágenes viejas sin uso..."
                      docker image prune -f

                      echo "→ Estado:"
                      docker compose ps

                      echo "✅ Despliegue completado!"
