name: Deploy Backend

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: SSH Deploy
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      echo "🚀 Iniciando despliegue..."

                      cd /var/www/inmobitwo/backend-inmobitwo

                      git pull origin main

                      echo "→ Instalando dependencias..."
                      rm -rf node_modules package-lock.json
                      npm install --production=false   # Instalamos todo para evitar problemas ESM

                      echo "→ Reiniciando aplicación..."
                      npx pm2 restart inmobitwo-api --update-env || npx pm2 start npm --name "inmobitwo-api" -- start

                      echo "→ Estado:"
                      npx pm2 list
                      echo "✅ Despliegue completado!"
